version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "your_password"
    ports:
      - "1435:1433"
    volumes:
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    command: /bin/bash -c "echo 'Starting SQL Server...'; /opt/mssql/bin/sqlservr & sleep 20; /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'your_password' -d master -i /docker-entrypoint-initdb.d/create-database.sql && tail -f /dev/null"

    networks:
      - mynetwork

  backend:
    build: ./
    depends_on:
      - sqlserver
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
    ports:
      - "3001:3001"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
